.PHONY: clean All

All:
	@echo "----------Building project:[ Chap_01 - Debug ]----------"
	@cd "Chap_01" && "$(MAKE)" -f  "Chap_01.mk"
clean:
	@echo "----------Cleaning project:[ Chap_01 - Debug ]----------"
	@cd "Chap_01" && "$(MAKE)" -f  "Chap_01.mk" clean
